### ISSUE TITLE
Credential issuance errors

### ISSUE THREAD

**Issue by nissimsan** [IBM-Blockchain-Identity/verify-creds-samples#14]
Hi, 

Very well worked through and convincing demo! A pleasure running through it. I'm getting errors when attempting to fetch the credentials, though (kinda the climax of the demo ;) ). 

The error vary slightly depending on whether I run the local docker apps (http://localhost:8091/account) or the online version (https://employer.livedemo.verify-creds.com/account). 

The local app throws me this error (both for the DMV and HR apps): 
```
Oh no!
Please refresh the page and try again.
Code: CREDENTIAL_NO_CREDENTIAL_DEFINITIONS
Reason: No credential definitions were found for issuer ibmhr!
```

The online app takes a bit longer and seems to be getting a bit further. But then throws this error: 
```
Oh no!
Please refresh the page and try again.
Code: CREDENTIAL_OFFER_FAILED
Reason: Credential issuance 027176337552 failed: Error: Still waiting on Credential to be accepted
```

I'm using the chrome extension client. 

Any hints at what I might be able to do to circumvent this? Or is there some defect out there causing this? 

Thanks!

**Comment by joevolleyball** [comment]
Hi @nissimsan, so issuing from ibmhr is failing I take it (locally)?  Does gov-dmv issue credentials and just ibmhr isn't?  Or is there a problem with both?  There are 3 things that need to happen before the agents can issue credentials:

* the issuer agents must be made issuers
* the issuer agents must have created a credential schema (or use one published by some other agent)
* the issuer agents must create a credential definition for each type of credential it plans to issue

Can you check to see if these are in place?  I assume that the agents are issuers otherwise I don't think that the containers would come up.  If you go to the <sample url:809x>/admin url, you can make sure that there is a schema and credential definition in place

**Comment by joevolleyball** [comment]
No feedback so closing
